numpy is fast becaues it use fixed type,contiguous memory
lists are slow



In [13]:
a=np.array([[4.0,5],[2,5.0]])
print(a)

<IPython.core.display.Javascript object>

[[4. 5.]
 [2. 5.]]


In [14]:
#dimention
a.ndim


2

In [15]:
#shape
a.shape

(2, 2)

In [16]:
a.dtype

dtype('float64')

In [17]:
a.itemsize

8

In [18]:
a.size

4

In [19]:
a.nbytes

32

In [28]:
b=np.array([[1,2,3],[1,3,5],[3,4,6],[8,0,9]])


<IPython.core.display.Javascript object>

In [36]:
b[1:3:1]

array([[1, 3, 5],
       [3, 4, 6]])

In [37]:
b[1:]

array([[1, 3, 5],
       [3, 4, 6],
       [8, 0, 9]])

In [41]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[:,1,:]

<IPython.core.display.Javascript object>

array([[3, 4],
       [7, 8]])

In [42]:
b[0,1,1]

4

In [44]:
b[0,1]=[3,8]

In [45]:
b[0,1]

array([3, 8])

In [53]:
np.ones((5,4,8),dtype='float')

<IPython.core.display.Javascript object>

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [55]:
np.full((2,2),23,dtype="float")

<IPython.core.display.Javascript object>

array([[23., 23.],
       [23., 23.]])

In [57]:
np.random.rand(4,3)

<IPython.core.display.Javascript object>

array([[0.15332047, 0.82459667, 0.84207381],
       [0.74874209, 0.04890055, 0.53025917],
       [0.49192065, 0.51823005, 0.93199535],
       [0.66091853, 0.03231911, 0.61223247]])

In [59]:
np.random.random_sample(b.shape)

<IPython.core.display.Javascript object>

array([[[0.77731204, 0.27819805],
        [0.62983034, 0.86388096]],

       [[0.94079047, 0.80024537],
        [0.32055995, 0.04588118]]])

In [60]:
np.identity(5)

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
arr=np.array([1,2,3])
z=np.repeat(arr,2,axis=0)
print(z)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1 1 2 2 3 3]
